#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generisanje Jupyter Notebooka:
Credit Card Fraud Detection - Duboko Ucenje i Neuronske Mreze

Pokreni: python create_notebook.py
Rezultat: fraud_detection.ipynb
"""

import nbformat
from nbformat.v4 import new_notebook, new_markdown_cell, new_code_cell

cells = []

# ===========================================================================
# CELL 0: Naslov
# ===========================================================================
cells.append(new_markdown_cell(
"# Primena Neuronskih Mreza za Predvidjanje Prevara u Finansijama\n"
"## Credit Card Fraud Detection -- Duboko Ucenje i Neuronske Mreze\n"
"\n"
"**Predmet:** Duboko ucenje i neuronske mreze\n"
"**Dataset:** [Kaggle -- Credit Card Fraud Detection]"
"(https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud)\n"
"\n"
"---\n"
"\n"
"### Zadatak i cilj\n"
"\n"
"U ovom radu sam se bavila detekcijom prevara u finansijskim transakcijama pomocu "
"neuronskih mreza. Glavni izazov ovog dataseta je sto je izrazito nebalansiran -- svega "
"0.17% transakcija su prevare -- pa je vecina rada zapravo posvecena tome kako se ta "
"nebalansiranost tretira, a ne samo izboru arhitekture mreze.\n"
"\n"
"Kroz notebook prolazim kroz nekoliko pristupa i pokusavam da objasnim zasto svaki sledeci "
"korak ima smisla:\n"
"\n"
"- zasto obicna accuracy ovde ne govori nista korisno,\n"
"- kako class weighting menja ponasanje modela,\n"
"- kako podesavanje praga odlucivanja (threshold tuning) utice na precision/recall,\n"
"- SMOTE kao alternativni nacin balansiranja podataka,\n"
"- i na kraju, autoencoder kao potpuno drugaciji, unsupervised pristup istom problemu.\n"
"\n"
"### O datasetu\n"
"\n"
"| Karakteristika | Vrednost |\n"
"|---|---|\n"
"| Ukupno transakcija | 284,807 |\n"
"| Fraudulentnih | 492 (0.172%) |\n"
"| Legitimnih | 284,315 (99.827%) |\n"
"| Karakteristike | V1-V28 (PCA), Time, Amount |\n"
"| Ciljna varijabla | Class (0=legitimno, 1=prevara) |\n"
"\n"
"Napomena: originalne karakteristike (V1-V28) su vec PCA transformisane od strane autora "
"dataseta radi zastite privatnosti korisnika, tako da ne znamo sta tacno predstavljaju -- "
"radimo sa njima kao sa \"crnom kutijom\"."
))

# ===========================================================================
# CELL 1: Importi
# ===========================================================================
cells.append(new_code_cell(
"# ============================================================\n"
"# 1. UVOZ BIBLIOTEKA\n"
"# ============================================================\n"
"\n"
"import numpy as np\n"
"import pandas as pd\n"
"import os\n"
"import warnings\n"
"warnings.filterwarnings('ignore')\n"
"\n"
"import matplotlib.pyplot as plt\n"
"import matplotlib.gridspec as gridspec\n"
"import seaborn as sns\n"
"\n"
"from sklearn.model_selection import train_test_split\n"
"from sklearn.preprocessing import StandardScaler\n"
"from sklearn.linear_model import LogisticRegression\n"
"from sklearn.dummy import DummyClassifier\n"
"from sklearn.metrics import (\n"
"    classification_report, confusion_matrix,\n"
"    roc_auc_score, average_precision_score,\n"
"    precision_recall_curve, f1_score,\n"
"    precision_score, recall_score, roc_curve\n"
")\n"
"from sklearn.utils.class_weight import compute_class_weight\n"
"from imblearn.over_sampling import SMOTE\n"
"\n"
"import tensorflow as tf\n"
"from tensorflow import keras\n"
"from tensorflow.keras import layers, callbacks, regularizers\n"
"\n"
"# Seed za reproduktibilnost - garantuje iste rezultate pri svakom pokretanju\n"
"SEED = 42\n"
"np.random.seed(SEED)\n"
"tf.random.set_seed(SEED)\n"
"\n"
"# Globalni stil grafika - tamna, profesionalna tema\n"
"plt.rcParams.update({\n"
"    'figure.facecolor': '#1a1a2e',\n"
"    'axes.facecolor':   '#16213e',\n"
"    'axes.edgecolor':   '#0f3460',\n"
"    'text.color':       'white',\n"
"    'axes.labelcolor':  'white',\n"
"    'xtick.color':      'white',\n"
"    'ytick.color':      'white',\n"
"    'grid.color':       '#0f3460',\n"
"    'grid.alpha':       0.5,\n"
"    'font.size':        11,\n"
"})\n"
"\n"
"# Paleta boja\n"
"FRAUD_COLOR     = '#e74c3c'   # Crvena - prevare\n"
"LEGIT_COLOR     = '#2ecc71'   # Zelena - legitimne\n"
"PRIMARY_COLOR   = '#3498db'   # Plava\n"
"SECONDARY_COLOR = '#9b59b6'   # Ljubicasta\n"
"\n"
"print(f'TensorFlow: {tf.__version__}')\n"
"print(f'NumPy:      {np.__version__}')\n"
"print(f'Pandas:     {pd.__version__}')\n"
"print('Sve biblioteke su ucitane.')\n"
))

# ===========================================================================
# CELL 2: Ucitavanje podataka - markdown
# ===========================================================================
cells.append(new_markdown_cell(
"## 2. Ucitavanje Podataka\n"
"\n"
"Dataset je dostupan na Kaggle-u (besplatno, ~150 MB):\n"
"\n"
"**Upute:**\n"
"1. Idi na: https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud\n"
"2. Preuzmi `creditcard.csv`\n"
"3. Postavi ga u isti folder kao ovaj notebook\n"
))

# ===========================================================================
# CELL 3: Ucitavanje podataka - kod
# ===========================================================================
cells.append(new_code_cell(
"# ============================================================\n"
"# 2. UCITAVANJE PODATAKA\n"
"# ============================================================\n"
"\n"
"# Pretrazi dataset u standardnim lokacijama\n"
"df = None\n"
"for path in ['creditcard.csv', 'data/creditcard.csv', '../creditcard.csv']:\n"
"    if os.path.exists(path):\n"
"        df = pd.read_csv(path)\n"
"        print(f'Dataset ucitan iz: {path}')\n"
"        break\n"
"\n"
"if df is None:\n"
"    raise FileNotFoundError(\n"
"        'creditcard.csv nije pronađen!\\n'\n"
"        'Preuzmi sa: https://www.kaggle.com/datasets/mlg-ulb/creditcardfraud'\n"
"    )\n"
"\n"
"print(f'Oblik dataseta: {df.shape}')\n"
"print(f'Nedostajuce vrednosti: {df.isnull().sum().sum()}')\n"
"df.head()\n"
))

# ===========================================================================
# CELL 4: Statistike
# ===========================================================================
cells.append(new_code_cell(
"# Detaljne statistike dataseta\n"
"n_legit = (df['Class'] == 0).sum()\n"
"n_fraud = (df['Class'] == 1).sum()\n"
"imbalance_ratio = n_legit / n_fraud\n"
"\n"
"print('=' * 60)\n"
"print('STATISTIKE DATASETA')\n"
"print('=' * 60)\n"
"print(f'Ukupno transakcija:      {len(df):>10,}')\n"
"print(f'Legitimnih (Class=0):    {n_legit:>10,}  ({n_legit/len(df)*100:.4f}%)')\n"
"print(f'Fraudulentnih (Class=1): {n_fraud:>10,}  ({n_fraud/len(df)*100:.4f}%)')\n"
"print(f'Imbalance ratio:         {imbalance_ratio:>10.0f} : 1')\n"
"print('=' * 60)\n"
"\n"
"dummy_acc = n_legit / len(df) * 100\n"
"print(f'\\nModel koji UVIJEK predvida legitimno => accuracy: {dummy_acc:.2f}%')\n"
"print('Ali bi nasao 0% prevara, sto znaci da accuracy ovde nije dobra metrika.')\n"
"\n"
"df[['Time', 'Amount', 'Class']].describe().round(3)\n"
))

# ===========================================================================
# CELL 5: EDA - markdown
# ===========================================================================
cells.append(new_markdown_cell(
"## 3. Eksploratorna Analiza Podataka (EDA)\n"
"\n"
"EDA nam pomaze da razumemo strukturu podataka pre modeliranja:\n"
"\n"
"1. **Distribucija klasa** -- vizualizacija class imbalance problema\n"
"2. **Analiza Amount i Time** -- razlike izmedju legitimnih i fraud transakcija\n"
"3. **Korelaciona matrica** -- odnosi izmedju karakteristika i target varijable\n"
"\n"
"> **Kljucno pitanje:** Zasto nam je EDA vazna?\n"
"> Razumevanje podataka direktno utice na izbor modela i metoda tretmana nebalansiranosti.\n"
))

# ===========================================================================
# CELL 6: Distribucija klasa
# ===========================================================================
cells.append(new_code_cell(
"# ============================================================\n"
"# EDA 1: DISTRIBUCIJA KLASA\n"
"# ============================================================\n"
"fig, axes = plt.subplots(1, 2, figsize=(14, 6))\n"
"fig.suptitle('Analiza Nebalansiranosti Klasa', fontsize=16, fontweight='bold')\n"
"\n"
"counts = df['Class'].value_counts().sort_index()\n"
"\n"
"# Bar chart\n"
"bars = axes[0].bar(\n"
"    ['Legitimne (0)', 'Prevare (1)'],\n"
"    counts.values,\n"
"    color=[LEGIT_COLOR, FRAUD_COLOR],\n"
"    width=0.5, edgecolor='white', linewidth=1.5, zorder=3\n"
")\n"
"axes[0].set_title('Broj transakcija po klasi', fontsize=13, fontweight='bold')\n"
"axes[0].set_ylabel('Broj transakcija')\n"
"axes[0].set_ylim(0, counts.max() * 1.18)\n"
"axes[0].grid(axis='y', alpha=0.3, zorder=0)\n"
"for bar, n in zip(bars, counts.values):\n"
"    axes[0].text(\n"
"        bar.get_x() + bar.get_width() / 2,\n"
"        bar.get_height() * 1.01,\n"
"        f'{n:,}\\n({n/len(df)*100:.3f}%)',\n"
"        ha='center', va='bottom', fontsize=11, fontweight='bold'\n"
"    )\n"
"\n"
"# Pie chart\n"
"_, _, autotexts = axes[1].pie(\n"
"    counts.values,\n"
"    labels=['Legitimne', 'Prevare'],\n"
"    colors=[LEGIT_COLOR, FRAUD_COLOR],\n"
"    autopct='%1.3f%%', startangle=90, explode=(0, 0.12),\n"
"    shadow=True, textprops={'color': 'white', 'fontsize': 11}\n"
")\n"
"for at in autotexts:\n"
"    at.set_fontweight('bold')\n"
"axes[1].set_title('Procentualni udeo klasa', fontsize=13, fontweight='bold')\n"
"\n"
"plt.tight_layout()\n"
"plt.savefig('01_class_distribution.png', dpi=150, bbox_inches='tight')\n"
"plt.show()\n"
"\n"
"print('ANALIZA DISTRIBUCIJE KLASA:')\n"
"print(f'  Imbalance ratio: {counts[0]:,} : {counts[1]:,} = {counts[0]/counts[1]:.0f}:1')\n"
"print()\n"
"print('  Model koji uvijek predvida legitimno:')\n"
"print(f'  - Accuracy:  {counts[0]/len(df)*100:.2f}%  (zvuci odlicno!)')\n"
"print(f'  - Recall:     0.00%  (ne detektuje NIJEDNU prevaru!)')\n"
"print('  Zakljucak: accuracy ovde nije odgovarajuca metrika.')\n"
"print('  Koristiti: Recall, Precision, F1-score, PR-AUC')\n"
))

# ===========================================================================
# CELL 7: Amount i Time analiza
# ===========================================================================
cells.append(new_code_cell(
"# ============================================================\n"
"# EDA 2: ANALIZA AMOUNT I TIME\n"
"# ============================================================\n"
"legit = df[df['Class'] == 0]\n"
"fraud = df[df['Class'] == 1]\n"
"\n"
"fig, axes = plt.subplots(2, 2, figsize=(16, 10))\n"
"fig.suptitle('Analiza varijabli Amount i Time po klasama', fontsize=15, fontweight='bold')\n"
"\n"
"axes[0, 0].hist(legit['Amount'], bins=100, color=LEGIT_COLOR, alpha=0.85, edgecolor='none', density=True)\n"
"axes[0, 0].set_title('Amount - Legitimne transakcije', fontsize=12, fontweight='bold')\n"
"axes[0, 0].set_xlabel('Iznos (EUR)'); axes[0, 0].set_ylabel('Gustoca'); axes[0, 0].set_xlim(0, 2500)\n"
"\n"
"axes[0, 1].hist(fraud['Amount'], bins=50, color=FRAUD_COLOR, alpha=0.85, edgecolor='none', density=True)\n"
"axes[0, 1].set_title('Amount - Prevare', fontsize=12, fontweight='bold')\n"
"axes[0, 1].set_xlabel('Iznos (EUR)'); axes[0, 1].set_ylabel('Gustoca')\n"
"\n"
"bp = axes[1, 0].boxplot(\n"
"    [legit['Amount'].clip(upper=500), fraud['Amount'].clip(upper=500)],\n"
"    labels=['Legitimne', 'Prevare'], patch_artist=True,\n"
"    medianprops=dict(color='yellow', linewidth=2.5)\n"
")\n"
"bp['boxes'][0].set_facecolor(LEGIT_COLOR + '60')\n"
"bp['boxes'][1].set_facecolor(FRAUD_COLOR + '60')\n"
"axes[1, 0].set_title('Box plot - Amount (clip 500 EUR)', fontsize=12, fontweight='bold')\n"
"axes[1, 0].set_ylabel('Iznos (EUR)')\n"
"\n"
"axes[1, 1].hist(legit['Time'], bins=100, color=LEGIT_COLOR, alpha=0.6, label='Legitimne', density=True, zorder=2)\n"
"axes[1, 1].hist(fraud['Time'], bins=50, color=FRAUD_COLOR, alpha=0.85, label='Prevare', density=True, zorder=3)\n"
"axes[1, 1].set_title('Distribucija Time po klasama', fontsize=12, fontweight='bold')\n"
"axes[1, 1].set_xlabel('Sekunde od prve transakcije'); axes[1, 1].set_ylabel('Gustoca')\n"
"axes[1, 1].legend()\n"
"\n"
"for ax in axes.flat:\n"
"    ax.set_facecolor('#16213e')\n"
"    for spine in ax.spines.values():\n"
"        spine.set_color('#0f3460')\n"
"\n"
"plt.tight_layout()\n"
"plt.savefig('02_amount_time.png', dpi=150, bbox_inches='tight')\n"
"plt.show()\n"
"\n"
"print('ANALIZA AMOUNT I TIME:')\n"
"print(f'  Legitimne - prosek: {legit[\"Amount\"].mean():.2f} EUR  | medijana: {legit[\"Amount\"].median():.2f} EUR')\n"
"print(f'  Prevare   - prosek: {fraud[\"Amount\"].mean():.2f} EUR  | medijana: {fraud[\"Amount\"].median():.2f} EUR')\n"
"print()\n"
"print('  -> Prevare imaju nizi prosek iznosa od legitimnih transakcija.')\n"
"print('     Prevaranti cesto testiraju karticu malim iznosima.')\n"
"print('  -> Time pokazuje 2 vala (dan/noc ritam), prevare su ravnomernije rasporedene.')\n"
))

# ===========================================================================
# CELL 8: Korelaciona matrica
# ===========================================================================
cells.append(new_code_cell(
"# ============================================================\n"
"# EDA 3: KORELACIONA MATRICA\n"
"# ============================================================\n"
"fig, axes = plt.subplots(1, 2, figsize=(20, 7))\n"
"fig.suptitle('Analiza Korelacija sa Target Varijablom', fontsize=15, fontweight='bold')\n"
"\n"
"class_corr = df.corr(numeric_only=True)['Class'].drop('Class').sort_values(key=abs, ascending=False)\n"
"bar_colors = [FRAUD_COLOR if v > 0 else LEGIT_COLOR for v in class_corr.values]\n"
"axes[0].barh(class_corr.index, class_corr.values, color=bar_colors, edgecolor='none', height=0.7)\n"
"axes[0].axvline(x=0, color='white', linewidth=1, alpha=0.5)\n"
"axes[0].set_title(\"Korelacija karakteristika sa 'Class'\", fontsize=13, fontweight='bold')\n"
"axes[0].set_xlabel('Pearsonov koeficijent korelacije')\n"
"axes[0].set_facecolor('#16213e')\n"
"\n"
"top_cols = list(class_corr.index[:14]) + ['Class']\n"
"corr_sub = df[top_cols].corr(numeric_only=True)\n"
"cmap = sns.diverging_palette(10, 130, s=80, l=55, n=256, as_cmap=True)\n"
"sns.heatmap(corr_sub, ax=axes[1], cmap=cmap, vmin=-0.8, vmax=0.8, center=0,\n"
"            linewidths=0.4, linecolor='#0f3460', annot=False, cbar_kws={'shrink': 0.8})\n"
"axes[1].set_title('Korelaciona matrica (top 14 + Class)', fontsize=13, fontweight='bold')\n"
"axes[1].tick_params(axis='x', rotation=45, labelsize=9)\n"
"axes[1].set_facecolor('#16213e')\n"
"\n"
"plt.tight_layout()\n"
"plt.savefig('03_correlation.png', dpi=150, bbox_inches='tight')\n"
"plt.show()\n"
"\n"
"print('TOP 10 KARAKTERISTIKA NAJKORELIRANIJIH SA Class:')\n"
"for i, (feat, val) in enumerate(class_corr.head(10).items(), 1):\n"
"    direction = 'pozitivna' if val > 0 else 'negativna'\n"
"    print(f'  {i:2}. {feat:>4}: {val:+.4f}  ({direction} korelacija)')\n"
))

# ===========================================================================
# CELL 9: Preprocessing - markdown
# ===========================================================================
cells.append(new_markdown_cell(
"## 4. Preprocessing\n"
"\n"
"### Koraci predprocesiranja (ispravnim redosledom)\n"
"\n"
"1. **Stratifikovana podela 70% / 15% / 15%** (train/val/test) -- PRVO\n"
"2. **Skaliranje `Amount` i `Time`** -- NAKON splita, samo na train skupu\n"
"\n"
"### Zasto split PRIJE skaliranja?\n"
"\n"
"Ovo je kljucno za izbegavanje **data leakage**. Ako bismo skalirali celi dataset\n"
"pre splita, scaler bi naucio mean/std iz test i val podataka -- model bi nesvesno\n"
"imao informacije o test skupu. Ispravno: `fit_transform` samo na train, `transform` na val/test.\n"
"\n"
"### Zasto stratifikovana podela?\n"
"\n"
"Kod izrazito nebalansiranih dataseta, nasumicna podela moze dovesti do toga da test skup\n"
"ima premalo fraud primera. **Stratifikacija garantuje isti udeo fraud transakcija** (~0.172%)\n"
"u svakom skupu -- kljucno za pouzdanu evaluaciju.\n"
))

# ===========================================================================
# CELL 10: Preprocessing - kod
# ===========================================================================
cells.append(new_code_cell(
"# ============================================================\n"
"# 4. PREPROCESSING\n"
"# ============================================================\n"
"\n"
"# 4.1 Priprema X i y (split PRIJE skaliranja -- sprecava data leakage!)\n"
"# Uklanjamo Amount i Time -- skaliracemo ih tek nakon train/val/test splita.\n"
"X_raw = df.drop('Class', axis=1).values\n"
"y     = df['Class'].values\n"
"\n"
"# 4.2 Stratifikovana podela 70% / 15% / 15%\n"
"# Radimo split na sirovim podacima -- scaler jos uvijek NIJE fittovan.\n"
"X_temp, X_test, y_temp, y_test = train_test_split(\n"
"    X_raw, y, test_size=0.15, random_state=SEED, stratify=y\n"
")\n"
"X_train, X_val, y_train, y_val = train_test_split(\n"
"    X_temp, y_temp, test_size=0.1765, random_state=SEED, stratify=y_temp\n"
")\n"
"\n"
"# 4.3 Skaliranje Amount i Time -- fit SAMO na train skupu!\n"
"# Ispravno: scaler uci mean/std samo od trening podataka.\n"
"# Pogresno bi bilo fit_transform(df) jer bi scaler video test i val podatke.\n"
"# Amount je zadnja kolona (indeks 29), Time je prva (indeks 0).\n"
"scaler_amount = StandardScaler()\n"
"scaler_time   = StandardScaler()\n"
"\n"
"X_train[:, 29] = scaler_amount.fit_transform(X_train[:, [29]]).ravel()\n"
"X_train[:, 0]  = scaler_time.fit_transform(X_train[:, [0]]).ravel()\n"
"\n"
"X_val[:, 29]   = scaler_amount.transform(X_val[:, [29]]).ravel()\n"
"X_val[:, 0]    = scaler_time.transform(X_val[:, [0]]).ravel()\n"
"X_test[:, 29]  = scaler_amount.transform(X_test[:, [29]]).ravel()\n"
"X_test[:, 0]   = scaler_time.transform(X_test[:, [0]]).ravel()\n"
"\n"
"print('Skaliranje izvrseno (bez data leakage).')\n"
"print(f'  Scaler fittovan samo na train skupu ({len(X_train):,} primera)')\n"
"print(f'  Amount -- mean iz train: {scaler_amount.mean_[0]:.4f}  std: {scaler_amount.scale_[0]:.4f}')\n"
"print()\n"
"print('Stratifikovana podela podataka:')\n"
"print(f'  Train:      {len(X_train):>7,}  | Fraud: {y_train.sum():>3}  ({y_train.mean()*100:.3f}%)')\n"
"print(f'  Validation: {len(X_val):>7,}  | Fraud: {y_val.sum():>3}  ({y_val.mean()*100:.3f}%)')\n"
"print(f'  Test:       {len(X_test):>7,}  | Fraud: {y_test.sum():>3}  ({y_test.mean()*100:.3f}%)')\n"
"\n"
"INPUT_DIM = X_train.shape[1]\n"
"print(f'\\n  Input dimenzija: {INPUT_DIM}')\n"
))

# ===========================================================================
# CELL 11: Evaluacione metrike - markdown
# ===========================================================================
cells.append(new_markdown_cell(
"## 5. Evaluacione Metrike\n"
"\n"
"### Zasto Accuracy NIJE dovoljna?\n"
"\n"
"Model koji uvijek predvida 'legitimno' => **99.83% accuracy**, ali **0% Recall** za prevare.\n"
"Takav model je potpuno beskoristan u praksi.\n"
"\n"
"### Koje metrike koristimo?\n"
"\n"
"| Metrika | Formula | Sta meri |\n"
"|---|---|---|\n"
"| **Precision** | TP/(TP+FP) | Od predvidjenih prevara, koliko su zaista prevare? |\n"
"| **Recall** | TP/(TP+FN) | Od svih pravih prevara, koliko je model pronasao? |\n"
"| **F1-Score** | 2*P*R/(P+R) | Harmonijska sredina Precision i Recall |\n"
"| **PR-AUC** | Povrsina PR krive | Opsta sposobnost detekcije pri svim pragovima |\n"
"| **ROC-AUC** | Povrsina ROC krive | Diskriminativna sposobnost modela |\n"
"\n"
"> **U detekciji prevara, Recall je kritican** -- propustena prevara (FN) je skuplja od\n"
"> laznog alarma (FP). **PR-AUC** je idealna sobirna metrika za nebalansirane datasete.\n"
))

# ===========================================================================
# CELL 12: Helper funkcije
# ===========================================================================
cells.append(new_code_cell(
"# ============================================================\n"
"# 5. HELPER FUNKCIJE ZA EVALUACIJU\n"
"# ============================================================\n"
"\n"
"def evaluate_model(model_name, y_true, y_pred, y_prob=None,\n"
"                   results_dict=None, show_plot=True, threshold=0.5):\n"
"    # Izracunavanje metrika\n"
"    precision = precision_score(y_true, y_pred, zero_division=0)\n"
"    recall    = recall_score(y_true, y_pred, zero_division=0)\n"
"    f1        = f1_score(y_true, y_pred, zero_division=0)\n"
"    pr_auc    = average_precision_score(y_true, y_prob) if y_prob is not None else 0.0\n"
"    roc_auc   = roc_auc_score(y_true, y_prob)           if y_prob is not None else 0.5\n"
"\n"
"    sep = '=' * 58\n"
"    print(f'\\n{sep}')\n"
"    print(f'  REZULTATI: {model_name}')\n"
"    print(f'{sep}')\n"
"    print(f'  Threshold:  {threshold:.4f}')\n"
"    print(f'  Precision:  {precision:.4f}  (od predvidjenih fraud, {precision*100:.1f}% su stvarno fraud)')\n"
"    print(f'  Recall:     {recall:.4f}  (pronasli smo {recall*100:.1f}% svih pravih prevara)')\n"
"    print(f'  F1-Score:   {f1:.4f}')\n"
"    print(f'  PR-AUC:     {pr_auc:.4f}')\n"
"    print(f'  ROC-AUC:    {roc_auc:.4f}')\n"
"    print(f'{sep}')\n"
"    print(f'\\n  Classification Report:')\n"
"    print(classification_report(y_true, y_pred,\n"
"                                 target_names=['Legitimno', 'Prevara'],\n"
"                                 zero_division=0))\n"
"\n"
"    if show_plot and y_prob is not None:\n"
"        fig, axes = plt.subplots(1, 3, figsize=(18, 5))\n"
"        fig.suptitle(f'Evaluacija: {model_name}', fontsize=14, fontweight='bold')\n"
"        for ax in axes:\n"
"            ax.set_facecolor('#16213e')\n"
"\n"
"        # 1. Confusion Matrix\n"
"        cm = confusion_matrix(y_true, y_pred)\n"
"        labels_cm = np.array([\n"
"            [f'TN\\n{cm[0,0]:,}', f'FP\\n{cm[0,1]:,}'],\n"
"            [f'FN\\n{cm[1,0]:,}', f'TP\\n{cm[1,1]:,}']\n"
"        ])\n"
"        sns.heatmap(cm, annot=labels_cm, fmt='', cmap='YlOrRd',\n"
"                    xticklabels=['Pred: Legit', 'Pred: Fraud'],\n"
"                    yticklabels=['Stvarno: Legit', 'Stvarno: Fraud'],\n"
"                    ax=axes[0], cbar=False, linewidths=2, linecolor='#1a1a2e',\n"
"                    annot_kws={'size': 13, 'weight': 'bold'})\n"
"        axes[0].set_title(f'Confusion Matrix\\n(threshold={threshold:.3f})', fontsize=12, fontweight='bold')\n"
"\n"
"        # 2. Precision-Recall kriva\n"
"        prec_v, rec_v, _ = precision_recall_curve(y_true, y_prob)\n"
"        axes[1].plot(rec_v, prec_v, color=PRIMARY_COLOR, linewidth=2.5)\n"
"        axes[1].fill_between(rec_v, prec_v, alpha=0.15, color=PRIMARY_COLOR)\n"
"        axes[1].axhline(y=y_true.mean(), color='gray', linestyle='--', alpha=0.7,\n"
"                        label=f'Baseline ({y_true.mean():.4f})')\n"
"        axes[1].scatter([recall], [precision], color=FRAUD_COLOR, s=150, zorder=5,\n"
"                        label=f'Threshold P={precision:.3f}, R={recall:.3f}')\n"
"        axes[1].set_title(f'PR Kriva  PR-AUC={pr_auc:.4f}', fontsize=12, fontweight='bold')\n"
"        axes[1].set_xlabel('Recall'); axes[1].set_ylabel('Precision')\n"
"        axes[1].legend(fontsize=9); axes[1].set_xlim([0,1]); axes[1].set_ylim([0,1.05])\n"
"\n"
"        # 3. ROC kriva\n"
"        fpr_v, tpr_v, _ = roc_curve(y_true, y_prob)\n"
"        axes[2].plot(fpr_v, tpr_v, color=SECONDARY_COLOR, linewidth=2.5, label=f'AUC={roc_auc:.4f}')\n"
"        axes[2].plot([0,1],[0,1], color='gray', linestyle='--', label='Slucajni model')\n"
"        axes[2].fill_between(fpr_v, tpr_v, alpha=0.15, color=SECONDARY_COLOR)\n"
"        axes[2].set_title(f'ROC Kriva  ROC-AUC={roc_auc:.4f}', fontsize=12, fontweight='bold')\n"
"        axes[2].set_xlabel('False Positive Rate'); axes[2].set_ylabel('True Positive Rate')\n"
"        axes[2].legend(fontsize=9)\n"
"\n"
"        plt.tight_layout()\n"
"        safe = model_name.lower().replace(' ', '_').replace('+', 'plus')\n"
"        plt.savefig(f'eval_{safe}.png', dpi=150, bbox_inches='tight')\n"
"        plt.show()\n"
"\n"
"    if results_dict is not None:\n"
"        results_dict[model_name] = {\n"
"            'Precision': round(precision, 4),\n"
"            'Recall':    round(recall, 4),\n"
"            'F1-Score':  round(f1, 4),\n"
"            'PR-AUC':    round(pr_auc, 4),\n"
"            'ROC-AUC':   round(roc_auc, 4),\n"
"            'Threshold': round(threshold, 4)\n"
"        }\n"
"    return {'precision': precision, 'recall': recall, 'f1': f1, 'pr_auc': pr_auc}\n"
"\n"
"\n"
"def plot_training(history, model_name):\n"
"    # Vizualizacija kriva treniranja - loss i PR-AUC\n"
"    fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n"
"    fig.suptitle(f'Krive treniranja -- {model_name}', fontsize=14, fontweight='bold')\n"
"    for ax in axes:\n"
"        ax.set_facecolor('#16213e')\n"
"\n"
"    axes[0].plot(history.history['loss'],     color=PRIMARY_COLOR, linewidth=2, label='Train')\n"
"    axes[0].plot(history.history['val_loss'], color=FRAUD_COLOR,   linewidth=2, label='Val')\n"
"    axes[0].set_title('Loss (Binary Cross-Entropy)', fontsize=12, fontweight='bold')\n"
"    axes[0].set_xlabel('Epoha'); axes[0].set_ylabel('Loss'); axes[0].legend()\n"
"\n"
"    if 'pr_auc' in history.history:\n"
"        axes[1].plot(history.history['pr_auc'],     color=PRIMARY_COLOR, linewidth=2, label='Train PR-AUC')\n"
"        axes[1].plot(history.history['val_pr_auc'], color=FRAUD_COLOR,   linewidth=2, label='Val PR-AUC')\n"
"        axes[1].set_title('PR-AUC tokom treniranja', fontsize=12, fontweight='bold')\n"
"        axes[1].set_xlabel('Epoha'); axes[1].set_ylabel('PR-AUC'); axes[1].legend()\n"
"\n"
"    plt.tight_layout()\n"
"    plt.savefig(f'train_{model_name.lower().replace(\" \",\"_\")}.png', dpi=150, bbox_inches='tight')\n"
"    plt.show()\n"
"\n"
"\n"
"def build_mlp(input_dim, hidden_layers=None, dropout=0.3, lr=0.001, name='MLP'):\n"
"    # Gradi MLP (Viselojni Perceptron) sa BatchNorm, ELU i Dropout\n"
"    # Arhitektura po sloju: Dense -> BatchNormalization -> ELU -> Dropout\n"
"    #\n"
"    # BatchNormalization : stabilizuje treniranje, ubrzava konvergenciju\n"
"    # ELU aktivacija     : izbegava dying neuron problem ReLU-a, glatke derivacije\n"
"    # L2 regularizacija  : penalizuje velike tezine (sprecava overfitting)\n"
"    # Dropout            : iskljucuje neurone tokom treniranja (regularizacija)\n"
"    if hidden_layers is None:\n"
"        hidden_layers = [64, 32, 16]\n"
"\n"
"    inp = keras.Input(shape=(input_dim,))\n"
"    x   = inp\n"
"    for i, units in enumerate(hidden_layers):\n"
"        x = layers.Dense(units, use_bias=False,\n"
"                         kernel_regularizer=regularizers.l2(1e-4),\n"
"                         name=f'dense_{i+1}')(x)\n"
"        x = layers.BatchNormalization(name=f'bn_{i+1}')(x)\n"
"        x = layers.ELU(name=f'elu_{i+1}')(x)\n"
"        x = layers.Dropout(dropout, name=f'drop_{i+1}')(x)\n"
"\n"
"    # Sigmoid izlaz - verovatnoca da je transakcija prevara [0, 1]\n"
"    out = layers.Dense(1, activation='sigmoid', name='output')(x)\n"
"    model = keras.Model(inp, out, name=name)\n"
"    model.compile(\n"
"        optimizer=keras.optimizers.Adam(lr),\n"
"        loss='binary_crossentropy',\n"
"        metrics=[\n"
"            'accuracy',\n"
"            keras.metrics.Precision(name='precision'),\n"
"            keras.metrics.Recall(name='recall'),\n"
"            keras.metrics.AUC(name='pr_auc', curve='PR')  # PR-AUC primarna metrika!\n"
"        ]\n"
"    )\n"
"    return model\n"
"\n"
"\n"
"def get_callbacks(patience=10):\n"
"    # EarlyStopping (prati val_pr_auc) + ReduceLROnPlateau\n"
"    return [\n"
"        callbacks.EarlyStopping(monitor='val_pr_auc', patience=patience,\n"
"                                mode='max', restore_best_weights=True, verbose=1),\n"
"        callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.5,\n"
"                                    patience=5, min_lr=1e-6, verbose=1)\n"
"    ]\n"
"\n"
"\n"
"# Inicijalizacija recnika za pracenje rezultata svih modela\n"
"ALL_RESULTS = {}\n"
"\n"
"print('Pomocne funkcije su definisane.')\n"
"print('ALL_RESULTS recnik inicijalizovan.')\n"
"print()\n"
"build_mlp(INPUT_DIM).summary()\n"
))

# ===========================================================================
# CELL 13: Dummy Baseline - markdown
# ===========================================================================
cells.append(new_markdown_cell(
"## 6. Dummy Baseline -- Naivni Klasifikator\n"
"\n"
"**Dummy klasifikator** uvijek predvida majority klasu (legitimno).\n"
"Koristimo ga iz dva razloga:\n"
"\n"
"1. **Donji benchmark** -- svaki pravi model mora biti bolji\n"
"2. **Demonstracija paradoksa accuracy** -- vizuelno dokazuje zasto accuracy varara\n"
"\n"
"| Metrika | Ocekivano |\n"
"|---|---|\n"
"| Accuracy | ~99.83% (varljivo visoka!) |\n"
"| Recall (fraud) | **0%** -- ne detektuje NIJEDNU prevaru! |\n"
"| F1-Score | **0%** -- beskoristan |\n"
))

# ===========================================================================
# CELL 14: Dummy Baseline - kod
# ===========================================================================
cells.append(new_code_cell(
"# ============================================================\n"
"# 6. DUMMY BASELINE\n"
"# ============================================================\n"
"\n"
"print('Treniranje Dummy Baseline modela...')\n"
"\n"
"# strategy='most_frequent' => uvijek predvida klasu 0 (legitimno)\n"
"dummy = DummyClassifier(strategy='most_frequent', random_state=SEED)\n"
"dummy.fit(X_train, y_train)\n"
"\n"
"y_pred_dummy = dummy.predict(X_test)\n"
"y_prob_dummy = dummy.predict_proba(X_test)[:, 1]\n"
"\n"
"acc_d = (y_pred_dummy == y_test).mean()\n"
"rec_d = recall_score(y_test, y_pred_dummy, zero_division=0)\n"
"print(f'\\nParadoks accuracy:')\n"
"print(f'  Accuracy: {acc_d*100:.2f}%  (zvuci dobro na prvi pogled)')\n"
"print(f'  Recall:   {rec_d*100:.2f}%  (ne detektuje nijednu prevaru)')\n"
"print()\n"
"print('Zakljucak: visoka accuracy bez visokog recall-a je u praksi beskorisna.')\n"
"\n"
"evaluate_model('Dummy Baseline', y_test, y_pred_dummy, y_prob_dummy,\n"
"               ALL_RESULTS, show_plot=False)\n"
"\n"
"print('\\nZakljucak:')\n"
"print('  Dummy model dramaticno demonstrira zasto accuracy nije dobra metrika.')\n"
"print('  Svaki sledeci model bi trebalo da bude bolji od ovoga.')\n"
))

# ===========================================================================
# CELL 15: Logistic Regression - markdown
# ===========================================================================
cells.append(new_markdown_cell(
"## 7. Logisticka Regresija -- Klasicni ML Baseline\n"
"\n"
"Logisticka regresija je **interpretabilan klasican ML model** koji nam sluzi kao benchmark.\n"
"\n"
"### Kljucni parametar: `class_weight='balanced'`\n"
"\n"
"Sklearn automatski izracunava optimalne tezine klasa:\n"
"\n"
"$$w_k = \\frac{N_{samples}}{N_{classes} \\cdot N_k}$$\n"
"\n"
"Za nas dataset: $w_{fraud} \\approx 289$  \n"
"**Model prima ~289x vecu kaznu za propustenu prevaru!**\n"
))

# ===========================================================================
# CELL 16: Logistic Regression - kod
# ===========================================================================
cells.append(new_code_cell(
"# ============================================================\n"
"# 7. LOGISTICKA REGRESIJA\n"
"# ============================================================\n"
"\n"
"print('Treniranje Logistic Regression modela...')\n"
"\n"
"lr_model = LogisticRegression(\n"
"    class_weight='balanced',  # Automatsko balansiranje klasa\n"
"    max_iter=1000, random_state=SEED,\n"
"    C=0.1, solver='lbfgs'     # L2 regularizacija\n"
")\n"
"lr_model.fit(X_train, y_train)\n"
"print('Model istreniran.')\n"
"\n"
"# Prikaz izracunatih class weights\n"
"cls = np.unique(y_train)\n"
"wts = compute_class_weight('balanced', classes=cls, y=y_train)\n"
"print(f'\\nClass weights:')\n"
"print(f'  Legitimne (0): {wts[0]:.4f}')\n"
"print(f'  Prevare    (1): {wts[1]:.4f}')\n"
"print(f'  Odnos: {wts[1]/wts[0]:.0f}x veca kazna za propustenu prevaru.')\n"
"\n"
"y_prob_lr = lr_model.predict_proba(X_test)[:, 1]\n"
"y_pred_lr = (y_prob_lr >= 0.5).astype(int)\n"
"\n"
"evaluate_model('Logistic Regression', y_test, y_pred_lr, y_prob_lr, ALL_RESULTS)\n"
"\n"
"print('\\nZakljucak:')\n"
"print('  Logisticka regresija sa balanced weights pokazuje dobar recall.')\n"
"print('  Neuronske mreze bi trebale nadjacati ovaj benchmark zahvaljujuci')\n"
"print('  sposobnosti ucenja nelinearnih obrazaca u podacima.')\n"
))

# ===========================================================================
# CELL 17: Basic MLP - markdown
# ===========================================================================
cells.append(new_markdown_cell(
"## 8. Basic MLP -- Neuronska Mreza Bez Balansiranja\n"
"\n"
"### Sta demonstriramo?\n"
"\n"
"Ovaj model ima **identicnu arhitekturu** kao Weighted MLP, ali se trenira\n"
"**bez ikakve kompenzacije za nebalansiranost klasa**.\n"
"\n"
"Cilj: pokazati da gradijentni spust minimizira ukupni loss, pa model **ignorise\n"
"fraud transakcije** (samo 0.17%) jer je lakse minimizirati gre ske na\n"
"legitimnim transakcijama (99.83%).\n"
"\n"
"> **Pedagoska vrednost:** Ovaj eksperiment motivise i opravdava upotrebu class weighting i SMOTE.\n"
"\n"
"### Arhitektura MLP\n"
"```\n"
"Input(30)\n"
"  -> Dense(64) -> BatchNorm -> ELU -> Dropout(0.3)\n"
"  -> Dense(32) -> BatchNorm -> ELU -> Dropout(0.3)\n"
"  -> Dense(16) -> BatchNorm -> ELU -> Dropout(0.3)\n"
"  -> Dense(1, sigmoid)\n"
"```\n"
))

# ===========================================================================
# CELL 18: Basic MLP - kod
# ===========================================================================
cells.append(new_code_cell(
"# ============================================================\n"
"# 8. BASIC MLP (bez class weighting)\n"
"# ============================================================\n"
"\n"
"print('Treniranje Basic MLP modela (BEZ class weighting)...')\n"
"print('Ocekivanje: los Recall zbog ignorisanja class imbalance!\\n')\n"
"\n"
"basic_mlp = build_mlp(INPUT_DIM, name='Basic_MLP')\n"
"\n"
"# Treniranje bez class_weight parametra\n"
"history_basic = basic_mlp.fit(\n"
"    X_train, y_train,\n"
"    validation_data=(X_val, y_val),\n"
"    epochs=100, batch_size=512,\n"
"    callbacks=get_callbacks(), verbose=1\n"
")\n"
"\n"
"print('\\nTreniranje zavrseno.')\n"
"plot_training(history_basic, 'Basic MLP')\n"
"\n"
"y_prob_basic = basic_mlp.predict(X_test, verbose=0).flatten()\n"
"y_pred_basic = (y_prob_basic >= 0.5).astype(int)\n"
"\n"
"evaluate_model('Basic MLP', y_test, y_pred_basic, y_prob_basic, ALL_RESULTS)\n"
"\n"
"print('\\nZakljucak:')\n"
"print('  Basic MLP BEZ class weightinga ima nizak Recall.')\n"
"print('  Model ignorise fraud transakcije jer je lakse minimizirati loss')\n"
"print('  uvijek predvidjajuci legitimne transakcije (99.83% su legitimne).')\n"
"print('  To bi trebalo da resi class weighting u sledecem koraku.')\n"
))

# ===========================================================================
# CELL 19: Weighted MLP - markdown
# ===========================================================================
cells.append(new_markdown_cell(
"## 9. Weighted MLP -- Neuronska Mreza Sa Ponderisanjem Klasa\n"
"\n"
"### Sta je Class Weighting?\n"
"\n"
"Weighted binary cross-entropy funkcija gubitka:\n"
"\n"
"$$\\mathcal{L} = -\\frac{1}{N}\\sum_{i=1}^{N}\\left[w_1 y_i \\log\\hat{y}_i + w_0(1-y_i)\\log(1-\\hat{y}_i)\\right]$$\n"
"\n"
"Greska na fraud primeru prima ~289x veci gradijent.\n"
"Model je **prinudjen da nauci karakteristike fraud transakcija**.\n"
"\n"
"U Kerasu, ovo je samo jedan parametar u `.fit()`: `class_weight=class_weight_dict`\n"
))

# ===========================================================================
# CELL 20: Weighted MLP - kod
# ===========================================================================
cells.append(new_code_cell(
"# ============================================================\n"
"# 9. WEIGHTED MLP (sa class weighting)\n"
"# ============================================================\n"
"\n"
"print('Treniranje Weighted MLP modela (SA class weighting)...')\n"
"\n"
"cls = np.unique(y_train)\n"
"wts = compute_class_weight('balanced', classes=cls, y=y_train)\n"
"class_weight_dict = dict(zip(cls, wts))\n"
"\n"
"print(f'\\nClass weights:')\n"
"print(f'  w[0] = {class_weight_dict[0]:.4f}  (legitimne)')\n"
"print(f'  w[1] = {class_weight_dict[1]:.4f}  (prevare)')\n"
"print(f'  -> Greska na fraud primeru je {class_weight_dict[1]/class_weight_dict[0]:.0f}x skuplja!\\n')\n"
"\n"
"weighted_mlp = build_mlp(INPUT_DIM, name='Weighted_MLP')\n"
"\n"
"# Jedina razlika od Basic MLP: class_weight parametar!\n"
"history_weighted = weighted_mlp.fit(\n"
"    X_train, y_train,\n"
"    validation_data=(X_val, y_val),\n"
"    epochs=100, batch_size=512,\n"
"    class_weight=class_weight_dict,  # <- kljucna razlika\n"
"    callbacks=get_callbacks(), verbose=1\n"
")\n"
"\n"
"print('\\nTreniranje zavrseno.')\n"
"plot_training(history_weighted, 'Weighted MLP')\n"
"\n"
"y_prob_weighted = weighted_mlp.predict(X_test, verbose=0).flatten()\n"
"y_pred_weighted = (y_prob_weighted >= 0.5).astype(int)\n"
"\n"
"evaluate_model('Weighted MLP', y_test, y_pred_weighted, y_prob_weighted, ALL_RESULTS)\n"
"\n"
"print('\\nZakljucak:')\n"
"print('  Weighted MLP pokazuje vidno poboljsanje u Recall-u u odnosu na Basic MLP.')\n"
"print('  Samo jedan parametar (class_weight) drasticno menja sposobnost modela')\n"
"print('  da detektuje prevare. Sledeci korak je threshold tuning.')\n"
))

# ===========================================================================
# CELL 21: Threshold Tuning - markdown
# ===========================================================================
cells.append(new_markdown_cell(
"## 10. Podesavanje Praga Klasifikacije (Threshold Tuning)\n"
"\n"
"### Sta je Threshold Tuning?\n"
"\n"
"Neuronska mreza daje **verovatnoce** u [0, 1]. Standard: `fraud if P >= 0.5`.\n"
"Ali prag **0.5 nije uvijek optimalan!**\n"
"\n"
"| Akcija | Recall | Precision | Efekat |\n"
"|---|---|---|---|\n"
"| t smanjimo | raste | pada | Vise prevara otkriveno, vise laznih alarma |\n"
"| t povecamo | pada | raste | Manje laznih alarma, propustamo vise prevara |\n"
"\n"
"### Nalazenje optimalnog praga\n"
"\n"
"Maksimiziramo F1-Score na **validacionom skupu**:\n"
"\n"
"$$t^* = \\arg\\max_t\\; F1(t) = \\arg\\max_t\\; \\frac{2 P(t) R(t)}{P(t) + R(t)}$$\n"
"\n"
"> **Nikad** ne koristiti test skup za threshold tuning -- to bi bio **data leakage**!\n"
))

# ===========================================================================
# CELL 22: Threshold Tuning - kod
# ===========================================================================
cells.append(new_code_cell(
"# ============================================================\n"
"# 10. THRESHOLD TUNING\n"
"# ============================================================\n"
"\n"
"print('Trazenje optimalnog threshold-a na validacionom skupu...')\n"
"\n"
"# Predvidjamo na VALIDACIONOM skupu - nikad na test skupu!\n"
"y_prob_val = weighted_mlp.predict(X_val, verbose=0).flatten()\n"
"\n"
"# P, R i thresholds za sve moguce pragove\n"
"prec_v, rec_v, thresh_v = precision_recall_curve(y_val, y_prob_val)\n"
"\n"
"# F1 za svaki prag (izbegavamo deljenje nulom)\n"
"f1_v = np.where(\n"
"    (prec_v[:-1] + rec_v[:-1]) > 0,\n"
"    2 * prec_v[:-1] * rec_v[:-1] / (prec_v[:-1] + rec_v[:-1]),\n"
"    0\n"
")\n"
"\n"
"opt_idx       = np.argmax(f1_v)\n"
"opt_threshold = thresh_v[opt_idx]\n"
"opt_p, opt_r, opt_f1 = prec_v[opt_idx], rec_v[opt_idx], f1_v[opt_idx]\n"
"\n"
"print(f'\\nOptimalni prag je pronadjen:')\n"
"print(f'  Standardni prag: 0.5000')\n"
"print(f'  Optimalni prag:  {opt_threshold:.4f}')\n"
"print(f'  Na optimalnom pragu (val skup):')\n"
"print(f'  Precision: {opt_p:.4f}  Recall: {opt_r:.4f}  F1: {opt_f1:.4f}')\n"
"\n"
"fig, axes = plt.subplots(1, 2, figsize=(16, 6))\n"
"fig.suptitle('Analiza Threshold-a -- Precision/Recall Trade-off', fontsize=14, fontweight='bold')\n"
"for ax in axes:\n"
"    ax.set_facecolor('#16213e')\n"
"\n"
"axes[0].plot(thresh_v, prec_v[:-1], color=PRIMARY_COLOR,   linewidth=2, label='Precision')\n"
"axes[0].plot(thresh_v, rec_v[:-1],  color=LEGIT_COLOR,     linewidth=2, label='Recall')\n"
"axes[0].plot(thresh_v, f1_v,        color=SECONDARY_COLOR, linewidth=2.5, linestyle='--', label='F1-Score')\n"
"axes[0].axvline(x=opt_threshold, color=FRAUD_COLOR, linewidth=2, linestyle=':',\n"
"                label=f'Optimalni ({opt_threshold:.3f})')\n"
"axes[0].axvline(x=0.5, color='gray', linewidth=1.5, linestyle=':', alpha=0.7,\n"
"                label='Standardni (0.5)')\n"
"axes[0].set_title('P, R i F1 vs Threshold', fontsize=13, fontweight='bold')\n"
"axes[0].set_xlabel('Threshold'); axes[0].set_ylabel('Vrednost')\n"
"axes[0].legend(fontsize=9); axes[0].set_xlim([0,1]); axes[0].set_ylim([0,1.05])\n"
"\n"
"pr_auc_v = average_precision_score(y_val, y_prob_val)\n"
"axes[1].plot(rec_v, prec_v, color=PRIMARY_COLOR, linewidth=2.5)\n"
"axes[1].fill_between(rec_v, prec_v, alpha=0.12, color=PRIMARY_COLOR)\n"
"axes[1].scatter([opt_r], [opt_p], color=FRAUD_COLOR, s=250, zorder=6,\n"
"                label=f'Optimalni prag ({opt_threshold:.3f})')\n"
"idx_05 = np.argmin(np.abs(thresh_v - 0.5))\n"
"axes[1].scatter([rec_v[idx_05]], [prec_v[idx_05]], color='gray', s=150, marker='D', zorder=5,\n"
"                label='Standardni (0.5)')\n"
"axes[1].set_title(f'PR Kriva  PR-AUC={pr_auc_v:.4f}', fontsize=13, fontweight='bold')\n"
"axes[1].set_xlabel('Recall'); axes[1].set_ylabel('Precision')\n"
"axes[1].legend(fontsize=9); axes[1].set_xlim([0,1]); axes[1].set_ylim([0,1.05])\n"
"\n"
"plt.tight_layout()\n"
"plt.savefig('threshold_tuning.png', dpi=150, bbox_inches='tight')\n"
"plt.show()\n"
"\n"
"# Primena optimalnog threshold-a na TEST skup\n"
"y_pred_tuned = (y_prob_weighted >= opt_threshold).astype(int)\n"
"evaluate_model('Weighted MLP + Threshold', y_test, y_pred_tuned,\n"
"               y_prob_weighted, ALL_RESULTS, threshold=opt_threshold)\n"
"\n"
"print(f'\\nZakljucak:')\n"
"print(f'  Smanjenjem praga sa 0.5 na {opt_threshold:.4f}:')\n"
"print(f'  -> Recall se povecao (detektujemo vise prevara)')\n"
"print(f'  -> Precision se blago smanjio (prihvatljiv trade-off)')\n"
"print(f'  -> Prag biramo prema poslovnom cilju (u zavisnosti od odnosa troska FN i FP).')\n"
))

# ===========================================================================
# CELL 23: SMOTE - markdown
# ===========================================================================
cells.append(new_markdown_cell(
"## 11. SMOTE -- Sinteticko Uvecanje Podataka\n"
"\n"
"**SMOTE** (Synthetic Minority Over-sampling Technique, Chawla et al., 2002)\n"
"kreira **nove sinteticke fraud primere** interpolacijom:\n"
"\n"
"```\n"
"Za svaki fraud primer x_i:\n"
"  1. Pronadji K=5 najblizih fraud suseda\n"
"  2. Nasumicno odaberi suseda x_j\n"
"  3. x_new = x_i + lambda * (x_j - x_i),  lambda u [0, 1]\n"
"```\n"
"\n"
"### SMOTE vs Class Weighting\n"
"\n"
"| Pristup | Prednost | Nedostatak |\n"
"|---|---|---|\n"
"| **Class Weighting** | Brz, bez modifikacije podataka | Samo menja loss |\n"
"| **SMOTE** | Kreira nove informacije; bolja generalizacija | Sporiji; rizik overfittinga |\n"
"\n"
"> **Pravilo:** SMOTE se primenjuje ISKLJUCIVO na **trening skup**!\n"
"> Validacioni i test skupovi moraju ostati originalni -- bez **data leakage**-a.\n"
))

# ===========================================================================
# CELL 24: SMOTE + MLP - kod
# ===========================================================================
cells.append(new_code_cell(
"# ============================================================\n"
"# 11. SMOTE + MLP\n"
"# ============================================================\n"
"\n"
"print('Primena SMOTE na trening skup...')\n"
"print(f'\\n  PRE SMOTE:')\n"
"print(f'  Legitimne: {(y_train==0).sum():,}  |  Prevare: {(y_train==1).sum():,}')\n"
"print(f'  Odnos: {(y_train==0).sum()/(y_train==1).sum():.0f}:1')\n"
"\n"
"# sampling_strategy=0.5 => n_fraud = 0.5 * n_legit nakon resample-a\n"
"smote = SMOTE(sampling_strategy=0.5, random_state=SEED, k_neighbors=5)\n"
"X_train_sm, y_train_sm = smote.fit_resample(X_train, y_train)\n"
"\n"
"n_new = (y_train_sm==1).sum() - (y_train==1).sum()\n"
"print(f'\\n  NAKON SMOTE:')\n"
"print(f'  Legitimne: {(y_train_sm==0).sum():,}  |  Prevare: {(y_train_sm==1).sum():,}')\n"
"print(f'  Kreirano novih sintetickih fraud primera: +{n_new:,}')\n"
"\n"
"# Vizualizacija efekta SMOTE\n"
"fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n"
"fig.suptitle('Efekat SMOTE na distribuciju trening skupa', fontsize=14, fontweight='bold')\n"
"for ax in axes:\n"
"    ax.set_facecolor('#16213e')\n"
"\n"
"for idx, (y_d, title) in enumerate([\n"
"    (y_train,    f'PRE SMOTE ({len(y_train):,} primera)'),\n"
"    (y_train_sm, f'NAKON SMOTE ({len(y_train_sm):,} primera)')\n"
"]):\n"
"    cnts = np.bincount(y_d)\n"
"    bars = axes[idx].bar(['Legitimne', 'Prevare'], cnts,\n"
"                         color=[LEGIT_COLOR, FRAUD_COLOR], edgecolor='white', linewidth=1.2)\n"
"    for bar, cnt in zip(bars, cnts):\n"
"        axes[idx].text(bar.get_x() + bar.get_width()/2, bar.get_height()*1.01,\n"
"                       f'{cnt:,}\\n({cnt/len(y_d)*100:.1f}%)',\n"
"                       ha='center', va='bottom', fontsize=10, fontweight='bold')\n"
"    axes[idx].set_title(title, fontsize=13, fontweight='bold')\n"
"    axes[idx].set_ylabel('Broj primera')\n"
"\n"
"plt.tight_layout()\n"
"plt.savefig('smote_effect.png', dpi=150, bbox_inches='tight')\n"
"plt.show()\n"
"\n"
"# Treniranje MLP na SMOTE datasetu\n"
"print('\\nTreniranje MLP na SMOTE datasetu...')\n"
"print('  Validacija na ORIGINALNIM podacima (bez data leakage)!\\n')\n"
"\n"
"smote_mlp = build_mlp(INPUT_DIM, name='SMOTE_MLP')\n"
"history_smote = smote_mlp.fit(\n"
"    X_train_sm, y_train_sm,          # SMOTE trening podaci\n"
"    validation_data=(X_val, y_val),   # Originalni val podaci!\n"
"    epochs=100, batch_size=512,\n"
"    callbacks=get_callbacks(), verbose=1\n"
")\n"
"\n"
"print('\\nSMOTE MLP treniranje zavrseno.')\n"
"plot_training(history_smote, 'SMOTE MLP')\n"
"\n"
"y_prob_smote = smote_mlp.predict(X_test, verbose=0).flatten()\n"
"y_pred_smote = (y_prob_smote >= 0.5).astype(int)\n"
"\n"
"evaluate_model('SMOTE + MLP', y_test, y_pred_smote, y_prob_smote, ALL_RESULTS)\n"
"\n"
"print('\\nZakljucak:')\n"
"print('  SMOTE kreira sinteticke primere koji pomazu modelu da bolje razume')\n"
"print('  karakteristike fraud transakcija. Poredenje sa Weighted MLP-om pokazuje')\n"
"print('  koja tehnika daje bolje rezultate na ovom datasetu.')\n"
))

# ===========================================================================
# CELL 25: Autoencoder - markdown
# ===========================================================================
cells.append(new_markdown_cell(
"## 12. Autoencoder -- Unsupervised Detekcija Anomalija\n"
"\n"
"### Potpuno drugaciji pristup!\n"
"\n"
"Autoencoder koristi **unsupervised** pristup:\n"
"\n"
"1. Trenira se **SAMO na legitimnim transakcijama** -- uci sta je 'normalno'\n"
"2. Za svaku novu transakciju, pokusava je rekonstruisati\n"
"3. **Legitimne** -> mali reconstruction error (model ih dobro rekonstruise)\n"
"4. **Fraud** -> **veliki reconstruction error** (razlikuju se od 'normalnog')\n"
"\n"
"### Arhitektura Autoencoder-a\n"
"```\n"
"Input(30) -> Dense(32)->BN->ELU -> Dense(16)->BN->ELU -> Dense(8) [latentni prostor]\n"
"          -> Dense(16)->BN->ELU -> Dense(32)->BN->ELU -> Dense(30) [rekonstrukcija]\n"
"```\n"
"\n"
"**Loss:** MSE izmedju originalnog i rekonstruisanog vektora\n"
"\n"
"| | Detalj |\n"
"|---|---|\n"
"| **Unsupervised** | Ne treba fraud labele za treniranje |\n"
"| **Generalizacija** | Robustan na nove, nevidjene vrste prevara |\n"
"| **Slabost** | Losiji PR-AUC od supervised modela kada postoje labele |\n"
))

# ===========================================================================
# CELL 26: Autoencoder build + train
# ===========================================================================
cells.append(new_code_cell(
"# ============================================================\n"
"# 12. AUTOENCODER ZA DETEKCIJU ANOMALIJA\n"
"# ============================================================\n"
"\n"
"print('Izgradnja Autoencoder modela...')\n"
"\n"
"# Treniramo SAMO na legitimnim transakcijama!\n"
"X_tr_legit  = X_train[y_train == 0]\n"
"X_val_legit = X_val[y_val == 0]\n"
"\n"
"print(f'  Legitimnih za treniranje: {len(X_tr_legit):,}')\n"
"print(f'  (Autoencoder ne vidi fraud primere tokom treniranja!)\\n')\n"
"\n"
"input_dim = X_train.shape[1]\n"
"\n"
"# ENCODER -- kompresuje podatke u latentni prostor\n"
"enc_in = keras.Input(shape=(input_dim,), name='encoder_input')\n"
"x = layers.Dense(32, use_bias=False)(enc_in)\n"
"x = layers.BatchNormalization()(x)\n"
"x = layers.ELU()(x)\n"
"x = layers.Dropout(0.1)(x)\n"
"x = layers.Dense(16, use_bias=False)(x)\n"
"x = layers.BatchNormalization()(x)\n"
"x = layers.ELU()(x)\n"
"\n"
"# Latentni prostor -- najuze grlo, komprimovana reprezentacija\n"
"latent = layers.Dense(8, activation='tanh', name='latent_space')(x)\n"
"\n"
"# DECODER -- rekonstruise original iz latentnog prostora\n"
"x = layers.Dense(16, use_bias=False)(latent)\n"
"x = layers.BatchNormalization()(x)\n"
"x = layers.ELU()(x)\n"
"x = layers.Dense(32, use_bias=False)(x)\n"
"x = layers.BatchNormalization()(x)\n"
"x = layers.ELU()(x)\n"
"\n"
"# Linearna aktivacija -- rekonstruise vrednosti koje mogu biti negativne\n"
"dec_out = layers.Dense(input_dim, activation='linear', name='reconstruction')(x)\n"
"\n"
"autoencoder = keras.Model(enc_in, dec_out, name='Autoencoder')\n"
"autoencoder.compile(optimizer=keras.optimizers.Adam(0.001), loss='mse')\n"
"autoencoder.summary()\n"
"print(f'\\nKompresija: {input_dim} -> 8 -> {input_dim}  ({input_dim//8}x faktor)')\n"
"\n"
"# TRENIRANJE -- ulaz = cilj (X -> rekonstruisi X)\n"
"print('\\nTreniranje autoencodera...\\n')\n"
"ae_cbs = [\n"
"    callbacks.EarlyStopping(monitor='val_loss', patience=10,\n"
"                            restore_best_weights=True, verbose=1),\n"
"    callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.5,\n"
"                                patience=5, min_lr=1e-6, verbose=1)\n"
"]\n"
"\n"
"# Kljucno: ulaz i cilj su ISTI (X, X)\n"
"history_ae = autoencoder.fit(\n"
"    X_tr_legit,  X_tr_legit,\n"
"    validation_data=(X_val_legit, X_val_legit),\n"
"    epochs=100, batch_size=256,\n"
"    callbacks=ae_cbs, verbose=1\n"
")\n"
"\n"
"print('\\nAutoencoder treniranje zavrseno.')\n"
"\n"
"fig, ax = plt.subplots(figsize=(10, 5))\n"
"ax.set_facecolor('#16213e')\n"
"ax.plot(history_ae.history['loss'],     color=LEGIT_COLOR, linewidth=2, label='Train MSE')\n"
"ax.plot(history_ae.history['val_loss'], color=FRAUD_COLOR, linewidth=2, label='Val MSE')\n"
"ax.set_title('Autoencoder -- Reconstruction Loss', fontsize=13, fontweight='bold')\n"
"ax.set_xlabel('Epoha'); ax.set_ylabel('MSE'); ax.legend()\n"
"plt.tight_layout()\n"
"plt.savefig('autoencoder_training.png', dpi=150, bbox_inches='tight')\n"
"plt.show()\n"
))

# ===========================================================================
# CELL 27: Autoencoder evaluacija
# ===========================================================================
cells.append(new_code_cell(
"# ============================================================\n"
"# EVALUACIJA AUTOENCODERA\n"
"# ============================================================\n"
"\n"
"print('Izracunavanje Reconstruction Error-a...')\n"
"\n"
"# Reconstruction error na TEST skupu (za finalnu evaluaciju i grafik)\n"
"X_test_recon = autoencoder.predict(X_test, verbose=0)\n"
"recon_err    = np.mean(np.square(X_test - X_test_recon), axis=1)\n"
"err_fraud    = recon_err[y_test == 1]\n"
"err_legit    = recon_err[y_test == 0]\n"
"\n"
"print('RECONSTRUCTION ERROR ANALIZA:')\n"
"print(f'  Legitimne -- mean: {err_legit.mean():.4f}  std: {err_legit.std():.4f}')\n"
"print(f'  Prevare   -- mean: {err_fraud.mean():.4f}  std: {err_fraud.std():.4f}')\n"
"print(f'  Odnos: {err_fraud.mean()/err_legit.mean():.1f}x veci error za prevare.')\n"
"print()\n"
"print('  -> Prevare imaju vidno veci reconstruction error.')\n"
"\n"
"# ─── THRESHOLD TUNING NA VALIDACIONOM SKUPU ─────────────────────────────\n"
"# Konsistentno sa Weighted MLP pristupom (Cell 22): prag trazimo na val skupu,\n"
"# a test skup koristimo iskljucivo za finalnu evaluaciju.\n"
"# Pogresno bi bilo: precision_recall_curve(y_test, recon_err) -- to je data leakage!\n"
"X_val_recon   = autoencoder.predict(X_val, verbose=0)\n"
"recon_err_val = np.mean(np.square(X_val - X_val_recon), axis=1)\n"
"\n"
"prec_val_ae, rec_val_ae, thresh_val_ae = precision_recall_curve(y_val, recon_err_val)\n"
"f1_val_ae = np.where(\n"
"    (prec_val_ae[:-1] + rec_val_ae[:-1]) > 0,\n"
"    2 * prec_val_ae[:-1] * rec_val_ae[:-1] / (prec_val_ae[:-1] + rec_val_ae[:-1]),\n"
"    0\n"
")\n"
"opt_ae   = np.argmax(f1_val_ae)\n"
"opt_t_ae = thresh_val_ae[opt_ae]\n"
"print(f'Optimalni threshold (iz VAL skupa): {opt_t_ae:.4f}')\n"
"\n"
"# Grafici (PR kriva na test skupu -- samo za vizualizaciju, ne za tuning)\n"
"fig, axes = plt.subplots(1, 2, figsize=(16, 6))\n"
"fig.suptitle('Autoencoder -- Evaluacija Reconstruction Error-a', fontsize=14, fontweight='bold')\n"
"for ax in axes:\n"
"    ax.set_facecolor('#16213e')\n"
"\n"
"clip_v = np.percentile(recon_err, 99)\n"
"axes[0].hist(err_legit.clip(max=clip_v), bins=100, alpha=0.7, color=LEGIT_COLOR, density=True,\n"
"             label=f'Legitimne (n={len(err_legit):,})')\n"
"axes[0].hist(err_fraud.clip(max=clip_v), bins=30, alpha=0.85, color=FRAUD_COLOR, density=True,\n"
"             label=f'Prevare (n={len(err_fraud):,})')\n"
"axes[0].set_title('Distribucija Reconstruction Error-a', fontsize=13, fontweight='bold')\n"
"axes[0].set_xlabel('MSE Reconstruction Error'); axes[0].set_ylabel('Gustoca')\n"
"axes[0].legend()\n"
"\n"
"pr_auc_ae  = average_precision_score(y_test, recon_err)\n"
"prec_ae, rec_ae, _ = precision_recall_curve(y_test, recon_err)\n"
"axes[1].plot(rec_ae, prec_ae, color=SECONDARY_COLOR, linewidth=2.5)\n"
"axes[1].fill_between(rec_ae, prec_ae, alpha=0.15, color=SECONDARY_COLOR)\n"
"axes[1].axvline(x=rec_val_ae[opt_ae], color=FRAUD_COLOR, linewidth=1.5, linestyle=':',\n"
"                label=f'Threshold iz val skupa = {opt_t_ae:.4f}')\n"
"axes[1].set_title(f'PR Kriva -- Autoencoder\\nPR-AUC={pr_auc_ae:.4f}', fontsize=13, fontweight='bold')\n"
"axes[1].set_xlabel('Recall'); axes[1].set_ylabel('Precision')\n"
"axes[1].legend(); axes[1].set_xlim([0,1]); axes[1].set_ylim([0,1.05])\n"
"\n"
"plt.tight_layout()\n"
"plt.savefig('autoencoder_eval.png', dpi=150, bbox_inches='tight')\n"
"plt.show()\n"
"\n"
"# Finalna evaluacija: threshold iz val, provera na test skupu\n"
"y_pred_ae = (recon_err >= opt_t_ae).astype(int)\n"
"evaluate_model('Autoencoder', y_test, y_pred_ae, recon_err, ALL_RESULTS, threshold=opt_t_ae)\n"
"\n"
"print('Zakljucak:')\n"
"print('  Autoencoder koristi potpuno drugaciji, unsupervised pristup.')\n"
"print(f'  PR-AUC = {pr_auc_ae:.4f} -- interesantno ga je uporediti sa supervised modelima.')\n"
"print('  Autoencoder je posebno vrijedan kada fraud labele NISU dostupne.')\n"
))

# ===========================================================================
# CELL 28: Finalna komparacija - markdown
# ===========================================================================
cells.append(new_markdown_cell(
"## 13. Finalna Komparacija Svih Modela\n"
"\n"
"### Pregled svih implementiranih pristupa\n"
"\n"
"| # | Model | Pristup | Tretman Imbalance |\n"
"|---|---|---|---|\n"
"| 1 | Dummy Baseline | Naive | Nema |\n"
"| 2 | Logistic Regression | Supervised, Linear | Class Weighting |\n"
"| 3 | Basic MLP | Supervised, Neural | Nema |\n"
"| 4 | Weighted MLP | Supervised, Neural | Class Weighting |\n"
"| 5 | Weighted MLP + Threshold | Supervised, Neural | Class Weighting + Threshold |\n"
"| 6 | SMOTE + MLP | Supervised, Neural | SMOTE Oversampling |\n"
"| 7 | Autoencoder | **Unsupervised**, Neural | Anomaly Detection |\n"
"\n"
"> **Pitanje za diskusiju:** Koji model je pobedio? Zasto?\n"
"> Odgovor zavisi od poslovnog cilja -- optimiziramo Recall, F1-Score ili PR-AUC?\n"
))

# ===========================================================================
# CELL 29: Finalna komparacija - kod
# ===========================================================================
cells.append(new_code_cell(
"# ============================================================\n"
"# 13. FINALNA KOMPARACIJA SVIH MODELA\n"
"# ============================================================\n"
"\n"
"results_df = pd.DataFrame(ALL_RESULTS).T\n"
"results_df = results_df[['Precision','Recall','F1-Score','PR-AUC','ROC-AUC','Threshold']]\n"
"results_df = results_df.round(4)\n"
"\n"
"print('=' * 75)\n"
"print('  FINALNA KOMPARACIJA MODELA (na test skupu)')\n"
"print('=' * 75)\n"
"print(results_df.to_string())\n"
"print('=' * 75)\n"
"\n"
"print('\\nNajbolji rezultat po metrici:')\n"
"for metric in ['Recall', 'Precision', 'F1-Score', 'PR-AUC']:\n"
"    best_m = results_df[metric].idxmax()\n"
"    print(f'  {metric:12}: {best_m:40}  ->  {results_df.loc[best_m, metric]:.4f}')\n"
"\n"
"# Bar chartovi za sve metrike\n"
"models   = list(results_df.index)\n"
"short_lbl = {\n"
"    'Dummy Baseline':           'Dummy',\n"
"    'Logistic Regression':      'LR',\n"
"    'Basic MLP':                'Basic\\nMLP',\n"
"    'Weighted MLP':             'Weighted\\nMLP',\n"
"    'Weighted MLP + Threshold': 'WMLP\\n+Thresh',\n"
"    'SMOTE + MLP':              'SMOTE\\n+MLP',\n"
"    'Autoencoder':              'Autoencoder'\n"
"}\n"
"xlabels = [short_lbl.get(m, m) for m in models]\n"
"x       = np.arange(len(models))\n"
"palcols = [FRAUD_COLOR,'#f39c12',PRIMARY_COLOR,LEGIT_COLOR,'#1abc9c',SECONDARY_COLOR,'#e67e22']\n"
"\n"
"fig, axes = plt.subplots(2, 2, figsize=(18, 12))\n"
"fig.suptitle('Finalna Komparacija Modela -- Credit Card Fraud Detection',\n"
"             fontsize=16, fontweight='bold')\n"
"axes = axes.flatten()\n"
"\n"
"for idx, metric in enumerate(['Recall','Precision','F1-Score','PR-AUC']):\n"
"    ax   = axes[idx]\n"
"    vals = results_df[metric].values\n"
"    bars = ax.bar(x, vals, color=palcols, edgecolor='white', linewidth=0.8, width=0.7, zorder=3)\n"
"    bars[np.argmax(vals)].set_edgecolor('gold')\n"
"    bars[np.argmax(vals)].set_linewidth(3)\n"
"    star = ' (*)' if metric in ['Recall','F1-Score','PR-AUC'] else ''\n"
"    ax.set_title(f'{metric}{star}', fontsize=14, fontweight='bold')\n"
"    ax.set_xticks(x); ax.set_xticklabels(xlabels, fontsize=9)\n"
"    ax.set_ylabel(metric); ax.set_ylim(0, 1.15)\n"
"    ax.set_facecolor('#16213e'); ax.grid(axis='y', alpha=0.3, zorder=0)\n"
"    for bar, val in zip(bars, vals):\n"
"        ax.text(bar.get_x()+bar.get_width()/2, bar.get_height()+0.02,\n"
"                f'{val:.3f}', ha='center', va='bottom', fontsize=9, fontweight='bold')\n"
"\n"
"plt.tight_layout()\n"
"plt.savefig('final_comparison_bars.png', dpi=150, bbox_inches='tight')\n"
"plt.show()\n"
"\n"
"# Radar Chart\n"
"radar_metrics = ['Precision','Recall','F1-Score','PR-AUC','ROC-AUC']\n"
"N      = len(radar_metrics)\n"
"angles = np.linspace(0, 2*np.pi, N, endpoint=False).tolist()\n"
"angles += angles[:1]\n"
"\n"
"fig, ax = plt.subplots(figsize=(10, 10), subplot_kw=dict(polar=True))\n"
"fig.suptitle('Radar Chart -- Komparacija Svih Modela', fontsize=15, fontweight='bold')\n"
"\n"
"for i, (mname, row) in enumerate(results_df.iterrows()):\n"
"    vals  = [row[m] for m in radar_metrics] + [row[radar_metrics[0]]]\n"
"    color = palcols[i % len(palcols)]\n"
"    ax.plot(angles, vals, color=color, linewidth=2.5,\n"
"            label=short_lbl.get(mname, mname))\n"
"    ax.fill(angles, vals, color=color, alpha=0.07)\n"
"\n"
"ax.set_xticks(angles[:-1]); ax.set_xticklabels(radar_metrics, fontsize=11)\n"
"ax.set_ylim(0,1); ax.set_yticks([0.2,0.4,0.6,0.8,1.0])\n"
"ax.grid(alpha=0.5)\n"
"ax.legend(loc='upper right', bbox_to_anchor=(1.35, 1.1), fontsize=9)\n"
"plt.tight_layout()\n"
"plt.savefig('final_comparison_radar.png', dpi=150, bbox_inches='tight')\n"
"plt.show()\n"
"\n"
"print('Sve vizualizacije su sacuvane.')\n"
))

# ===========================================================================
# CELL 30: Zakljucak
# ===========================================================================
cells.append(new_markdown_cell(
"## 14. Zakljucak\n"
"\n"
"### Sta sam naucila iz ovog rada\n"
"\n"
"Najvazniji uvid iz celog ovog rada je da accuracy sama po sebi ne govori skoro nista\n"
"kod ovako nebalansiranog dataseta. Dummy model koji uvek predvidja \"legitimno\" ima\n"
"~99.83% accuracy, a ne pronalazi nijednu prevaru -- sto je bio i pocetni motiv da se\n"
"u nastavku rada oslanjam na Recall, Precision, F1 i PR-AUC, a ne na accuracy.\n"
"\n"
"### Odgovori na pitanja koja sam sebi postavila tokom rada\n"
"\n"
"**Zasto accuracy nije dovoljna?**\n"
"Kod ovako nebalansiranih klasa, model koji samo \"pogadja\" vecinsku klasu ima skoro\n"
"savrsenu accuracy, a u praksi je beskoristan. Zato su Recall, Precision i PR-AUC\n"
"mnogo relevantniji za ovaj problem.\n"
"\n"
"**Kako class imbalance utice na treniranje?**\n"
"Videlo se direktno kod Basic MLP-a: gradijentni spust minimizira ukupan loss, a kako\n"
"je 99.83% primera legitimno, model najlakse dolazi do niskog loss-a tako sto skoro\n"
"uvek predvidja \"legitimno\" -- fraud primeri (samo 492 od 284,807) imaju premalen uticaj.\n"
"\n"
"**Da li class weighting zaista pomaze?**\n"
"Da, i to prilicno vidljivo -- Weighted MLP je imao znatno bolji Recall od Basic MLP-a\n"
"uz istu arhitekturu, sto potvrdjuje da je razlog bio upravo u tretmanu nebalansiranosti,\n"
"a ne u samoj mrezi.\n"
"\n"
"**Sta threshold tuning menja?**\n"
"Pomeranjem praga ispod 0.5 se podize Recall po cenu Precision-a. U ovom radu sam prag\n"
"birala tako da maksimizuje F1 na validacionom skupu, ali u stvarnom sistemu bi taj\n"
"izbor verovatno zavisio i od toga koliko banci/kompaniji kosta propustena prevara u\n"
"odnosu na lazni alarm -- to je vise poslovna nego tehnicka odluka.\n"
"\n"
"**Kako se autoencoder poredi sa supervised pristupima?**\n"
"Rezultati u tabeli u prethodnoj celiji pokazuju konkretno poredjenje po PR-AUC.\n"
"Ono sto mi je zanimljivo je da autoencoder uopste ne vidi fraud primere tokom\n"
"treniranja, a opet uspeva da ih razlikuje na osnovu reconstruction error-a -- to je\n"
"korisno u scenariju gde labele uopste ne bi bile dostupne.\n"
"\n"
"### Ogranicenja rada\n"
"\n"
"Nekoliko stvari bih istakla kao ogranicenje: hiperparametri (broj slojeva,\n"
"learning rate, SMOTE odnos) nisu sistematski tunirani (npr. grid/random search), vec su\n"
"postavljeni na razumne, uobicajene vrednosti. Takodje, rezultati zavise od jednog train/val/test\n"
"splita (fiksiran SEED), pa bi se za ozbiljniju procenu moglo koristiti i cross-validation.\n"
"\n"
"### Sta bi bilo zanimljivo probati dalje\n"
"\n"
"- Focal Loss kao alternativu class weightingu\n"
"- Ensemble pristup (npr. kombinovanje Weighted MLP-a i Autoencoder-a)\n"
"- SHAP vrednosti, da se vidi koje karakteristike najvise uticu na pojedinacnu predikciju\n"
"- Eventualno LSTM/sekvencijalni model, ako bi se transakcije posmatrale hronoloski po korisniku\n"
"\n"
"---\n"
"\n"
"*Ovaj notebook je radjen kao projekat/seminarski rad za predmet Duboko ucenje i neuronske mreze.*\n"
))

# ===========================================================================
# KREIRANJE I PISANJE NOTEBOOKA
# ===========================================================================
nb = new_notebook(cells=cells)
nb.metadata.update({
    'kernelspec': {
        'display_name': 'Python 3',
        'language': 'python',
        'name': 'python3'
    },
    'language_info': {
        'codemirror_mode': {'name': 'ipython', 'version': 3},
        'file_extension': '.py',
        'mimetype': 'text/x-python',
        'name': 'python',
        'version': '3.10.0'
    }
})

output = 'fraud_detection.ipynb'
with open(output, 'w', encoding='utf-8') as f:
    nbformat.write(nb, f)

print(f"Notebook uspesno kreiran: {output}")
print(f"Broj celija: {len(cells)}")
print()
print("Sledeci koraci:")
print("  1. pip install -r requirements.txt")
print("  2. Preuzmi creditcard.csv sa Kaggle-a i postavi u ovaj folder")
print("  3. jupyter lab fraud_detection.ipynb")
